name: elevenohthreeohfour
favicon: null
layout_spectrum: 0.9418020269367844
typography_spectrum: 0.44523082044906914
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#505662'
    - '#ffffff'
    - '#c0c7d1'
    - '#9197a3'
    - '#2f3a50'
  brandStrength: 0.625
  lightness: 0.5625
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
